return {
	{
		"williamboman/mason.nvim",
		commit = "4da89f3",
		opts = {
			ensure_installed = {
				"actionlint",
				"ansible-language-server",
				"ansible-lint",
				"antlers-language-server",
				"black",
				"bash-language-server",
				"blade-formatter",
				"docker-compose-language-service",
				"dockerfile-language-server",
				"dot-language-server",
				"emmet-ls",
				"eslint_d",
				"flake8",
				"hadolint",
				"html-lsp",
				-- "intelephense",
				"phpactor",
				"php-debug-adapter",
				"phpcs",
				"php-cs-fixer",
				"vue-language-server",
				"vtsls",
				"pint",
				"prettierd",
				"pyright",
				"rustywind",
				"shellcheck",
				"shfmt",
				"stylua",
				"tailwindcss-language-server",
				"typescript-language-server",
			},
		},
	},
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	event = "VeryLazy",
	dependencies = {
		"williamboman/mason.nvim",
		"williamboman/mason-lspconfig.nvim",
		"neovim/nvim-lspconfig",
		"jay-babu/mason-nvim-dap.nvim",
		"rcarriga/nvim-dap-ui",
		"mfussenegger/nvim-dap",
		"nvim-neotest/nvim-nio",
		"nvimtools/none-ls.nvim",
		"nvimtools/none-ls-extras.nvim",
		"zapling/mason-lock.nvim",
		"folke/lazydev.nvim",
	},
	{ "williamboman/mason-lspconfig.nvim", commit = "1a31f82" },
}
